Payrollfix_poc/Controllers/EmployeeController.cs
using Microsoft.AspNetCore.Mvc;
using Payrollfix_poc.Filters;
using Payrollfix_poc.IRepository;
using Payrollfix_poc.Models;
using Payrollfix_poc.ViewModels;

namespace Payrollfix_poc.Controllers
{
    /// <summary>
    /// This Controller contains 7 Action methods:
    /// <para><see cref="Dashboard"/></para>
    /// <para><see cref="ResetPassword(ResetPasswordViewModel)"/></para>
    /// <para><see cref="Organization(string)"/></para>
    /// <para><see cref="OrganizationChart"/></para>
    /// <para><see cref="LoginDetails"/></para>
    /// <para><see cref="AM"/></para>
    /// <para><see cref="MyTeam"/></para>
    /// </summary>

    [CustomAuthorize]
	[AsyncCustomResultFilter]
	public class EmployeeController : Controller
    {
        public readonly IEmployeeRepository _employeeRepository;
        public readonly IAdminRepository _adminRepository;

        public EmployeeController(IEmployeeRepository repository,IAdminRepository admin)
        {
            _employeeRepository = repository;
            _adminRepository = admin;
        }
        public async Task<IActionResult> Dashboard()
        {
            var employeeId = HttpContext.Session.GetInt32("EmployeeId"); // prior verification

            var employee = await _employeeRepository.GetEmployeeDetails(employeeId);

            if (employee == null)
            {
                return NotFound(); // Handle not found
            }

            ViewData["ActiveDashboard"] = "active";
            return View(employee); // Pass the single employee data to the view
        }
        [HttpGet]
        public IActionResult ResetPassword()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> ResetPassword(ResetPasswordViewModel model)
        {
            int? EmpId = HttpContext.Session.GetInt32("EmployeeId");
            if (ModelState.IsValid)
            {
                // Get the logged-in employee (or use the employee ID)
                if (EmpId != 0)
                {
                    var employee = await _employeeRepository.GetEmployeeById(EmpId);

                    if (employee == null)
                    {
                        ModelState.AddModelError("", "User not found.");
                        return View(model);
                    }

                    // Verify the old password

                    if (model.OldPassword != employee.Password)
                    {
                        ModelState.AddModelError("OldPassword", "The old password is incorrect.");
                        return View(model);
                    }

                    // Check if new password is different from the old password
                    if (model.NewPassword == model.OldPassword)
                    {
                        ModelState.AddModelError("NewPassword", "New password cannot be the same as the old password.");
                        return View(model);
                    }

                    employee.Password = model.NewPassword;
                    await _adminRepository.Save(employee);

                    // Optionally redirect or show confirmation
                    ViewBag.Message = "Your password has been successfully updated.";
                    return View("ResetConfirmation");
                }
            }

            return View(model);
        }

        public async Task<IActionResult> Organization(string name)
        {
			var id = HttpContext.Session.GetInt32("EmployeeId");
			ViewData["ActiveEmployee"] = "active";
			// Get all employees if no search query is provided
			var employees = await _employeeRepository.GetEmployeeList();

            // If a search query is provided, filter the employees
            if (!string.IsNullOrEmpty(name))
            {
                employees = employees
                            .Where(e => e.FirstName.Contains(name, StringComparison.OrdinalIgnoreCase) ||
                                        e.LastName.Contains(name, StringComparison.OrdinalIgnoreCase))
                            .ToList();

                if (employees.Count == 0)
                {
                    ViewBag.ErrorMessage = "No employee found with the given name.";
                }
            }

            // If there's only one employee found in the search, show detailed view for that employee
            if (employees.Count == 1)
            {
                return View("EmployeeDetails", employees.First());
            }

            // Pass the list of employees to the view
            return View(employees);
        }

        public async Task<IActionResult> OrganizationChart()
        {
			var id = HttpContext.Session.GetInt32("EmployeeId");
			var employees = await _employeeRepository.GetEmployeeList();
			ViewData["ActiveEmployee"] = "active";
			// Pass the employees to the view
			return View(employees);
        }

        public async Task<IActionResult> LoginDetails()
        {
            var employeeId = HttpContext.Session.GetInt32("EmployeeId");

            var activities = await _employeeRepository.GetEntitiesByCondition<LoginActivity>(e => e.EmployeeId == employeeId);

            if (activities == null || !activities.Any())
            {
                // Handle the case where no activities are found for the employee
                return NotFound("No login activities found for the specified employee.");
            }

			ViewData["ActiveLoginDetails"] = "active";
            return View(activities);  // Passing the login activities to the view
        }

        public async Task<IActionResult> AM()
        {
            var id = HttpContext.Session.GetInt32("EmployeeId");

            var attendance = await _employeeRepository.GetEntitiesByCondition<Attandence>(e => e.EmployeeId ==  id);
            ViewData["ActiveAttendance"] = "active";

            return View(attendance);
        }

        public async Task<IActionResult> MyTeam()
        {
            var CurrentManagerId = HttpContext.Session.GetInt32("EmployeeId");

            // Get the list of employees who report to the current manager
            var employees = await _employeeRepository.GetEntitiesByCondition<Employee>(e => e.ManagerId == CurrentManagerId);

			ViewData["ActiveMyTeam"] = "active";
            return View(employees);
        }

    }
}

Payrollfix_poc/Controllers/ExpenseController.cs
using Microsoft.AspNetCore.Mvc;
using Payrollfix_poc.Models;
using Payrollfix_poc.IRepository;
using Payrollfix_poc.Filters;

namespace Payrollfix_poc.Controllers
{
    [CustomAuthorize]
	[AsyncCustomResultFilter]
	public class ExpenseController : Controller
    {
        public readonly IEmployeeRepository _employeeRepository;
        public readonly IAdminRepository _adminRepository;
        public ExpenseController(IEmployeeRepository repository, IAdminRepository admin)
        {
            _employeeRepository = repository;
            _adminRepository = admin;
        }

        // GET: Show all expenses grouped by month and week
        public async Task<IActionResult> Index()
        {
            var expenses = await _employeeRepository.GetExpenseList();
            var id = HttpContext.Session.GetInt32("EmployeeId");
            var groupedExpenses = await _employeeRepository.GroupedExpenses(id, expenses);
			ViewData["ActiveExpenses"] = "active";
            return View(groupedExpenses);
        }

        // GET: Add Expense
        public IActionResult AddExpense()
        {
            return PartialView("_AddExpense");
        }

        // POST: Save Expense
        [HttpPost]
        public async Task<IActionResult> AddExpense(Expense model)
        {
            if (ModelState.IsValid)
            {
                var employeeId = HttpContext.Session.GetInt32("EmployeeId");
                if (employeeId == null)
                {
                    return RedirectToAction("Login", "Account");
                }

                model.EmployeeId = employeeId.Value;  // Assign employee ID
                await _adminRepository.Save(model);

                return RedirectToAction("Index");
            }

            return PartialView("_AddExpense", model);
        }

    }
}

Payrollfix_poc/Controllers/LeavesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.SignalR;
using Payrollfix_poc.Data;
using Payrollfix_poc.Filters;
using Payrollfix_poc.IRepository;
using Payrollfix_poc.Models;
using Payrollfix_poc.SignalR_Hub;
using Payrollfix_poc.ViewModels;

namespace Payrollfix_poc.Controllers
{
    [CustomAuthorize]
	[AsyncCustomResultFilter]
	public class LeaveController : Controller
    {
        private readonly IEmployeeRepository _employeeRepository;
        private readonly IAdminRepository _adminRepository;
        private readonly IHubContext<NotificationHub> _hubContext;
        public LeaveController(PayRollFix_pocContext context,IEmployeeRepository repository,IAdminRepository admin, IHubContext<NotificationHub> hubContext)
        {
            _employeeRepository = repository;
            _adminRepository = admin;
            _hubContext = hubContext;
        }

        // Action method to retrieve leaves for a specific employee
        public async Task<IActionResult> LeaveDetails()
        {
            var employeeId = HttpContext.Session.GetInt32("EmployeeId");

            // Get leave details for the specific employee
            var leaves = await _employeeRepository.GetLeaves(employeeId);

            // Get leave balance for the specific employee
            var leaveBalance = await _employeeRepository.GetLeaveBalance(employeeId);

            // Combine both into a view model
            var model = new LeaveViewModel
            {
                Leaves = leaves,
                LeaveBalance = leaveBalance
            };
			ViewData["ActiveLeaves"] = "active";
			return View(model);
        }

		[HttpPost]
		public async Task<IActionResult> ApplyLeave(Leave leave)
		{
			if (ModelState.IsValid)
			{
				leave.EmployeeId = (int)HttpContext.Session.GetInt32("EmployeeId");
				// Get the employee's leave balance
				var leaveBalance = await _employeeRepository.GetLeaveBalance(leave.EmployeeId);

				// Calculate the total leave days
				int totalLeaveDays = (leave.EndDate - leave.StartDate).Days + 1;

				// Check if the employee has enough remaining days
				if (totalLeaveDays > (leaveBalance.MaxDays - leaveBalance.UsedDays))
				{
					ViewBag.Message="You don't have enough leave days.";
					return View("_ApplyLeave");
				}

				// Update the used days in leave balance
				leaveBalance.UsedDays += totalLeaveDays;

				// Add the new leave to the database
				await _adminRepository.Save(leave);
                await _adminRepository.Update(leaveBalance);

				// Redirect back to the leave overview page
				return RedirectToAction("LeaveDetails");
			}
			// Return the same view with validation errors
			return View("_ApplyLeave", leave);
		}

        public async Task<IActionResult> Permission(int employeeId)
        {
			var id = HttpContext.Session.GetInt32("EmployeeId");
			var employee = await _employeeRepository.GetEmployeeDetails(employeeId);

            if (employee == null)
            {
                return NotFound();
            }

            var pendingLeaves = employee.Leaves
                .Where(l => l.Status == "Pending")
                .ToList();

			return View(pendingLeaves);
        }
        // Action to approve leave
        [HttpPost]
        public async Task<IActionResult> ApproveLeave(int leaveId)
        {
            var leave = await _employeeRepository.GetLeaveById(leaveId);
            if (leave == null)
            {
                return NotFound();
            }
			string userId = HttpContext.Session.GetString("EmployeeId");
			// Approve the leave and save changes
			leave.Status = "Approved";
            await _adminRepository.Update(leave);
            await _hubContext.Clients.User(userId).SendAsync("ReceiveLeaveStatusUpdate", leaveId.ToString(), "Approved");

            return RedirectToAction("Permission", new {employeeId=leave.EmployeeId});
        }
        // Action to reject leave
        [HttpPost]
        public async Task<IActionResult> RejectLeave(int leaveId)
        {
            var leave = await _employeeRepository.GetLeaveById(leaveId);
            if (leave == null)
            {
                return NotFound();
            }

            // Reject the leave and save changes
            leave.Status = "Rejected";
            await _adminRepository.Update(leave);

            return RedirectToAction("Permission", new { employeeId = leave.EmployeeId });
        }
    }
}

Payrollfix_poc/Controllers/TimesheetController.cs
using Microsoft.AspNetCore.Mvc;
using Payrollfix_poc.Filters;
using Payrollfix_poc.Models;
using Payrollfix_poc.IRepository;

namespace Payrollfix_poc.Controllers
{
	[CustomAuthorize]
	[AsyncCustomResultFilter]
	public class TimesheetController : Controller
	{
		private readonly IEmployeeRepository _employeeRepository;
		private readonly IAdminRepository _adminRepository;

		public TimesheetController(IEmployeeRepository repository,IAdminRepository adminRepository)
		{
			_employeeRepository=repository;
			_adminRepository=adminRepository;
		}
		// Action to display all timesheets
		public async Task<IActionResult> TimesheetList()
		{
			var id = HttpContext.Session.GetInt32("EmployeeId");
			var timesheets = await _employeeRepository.GetTimesheetList(id);
            ViewData["ActiveTimesheet"] = "active";
            return View(timesheets);
		}
		// GET: Timesheet/Create
		public IActionResult Create()
		{
			Timesheet timesheet = new Timesheet(); 
			int id=(int)HttpContext.Session.GetInt32("EmployeeId");
			timesheet.EmployeeId = id;
			return View(timesheet);
		}

		// POST: Timesheet/Create
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Create(Timesheet timesheet)
		{
			if (ModelState.IsValid)
			{
				await _adminRepository.Save(timesheet);
				return RedirectToAction("TimesheetList");
			}
			return View(timesheet);
		}

		// GET: Timesheet/Edit/5
		public async Task<IActionResult> Edit(int id)
		{
			Timesheet timesheet = new Timesheet();
			int Empid = (int)HttpContext.Session.GetInt32("EmployeeId");
			//timesheet.EmployeeId = id;
			timesheet = await _employeeRepository.GetTimesheetById(id);
			if (timesheet == null)
			{
				return NotFound();
			}
			return View(timesheet);
		}

		// POST: Timesheet/Edit/5
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Edit(int id, Timesheet timesheet)
		{
			if (id != timesheet.TimesheetId)
			{
				return NotFound();
			}

			timesheet.EmployeeId = (int)HttpContext.Session.GetInt32("EmployeeId");
			if (ModelState.IsValid)
			{
				await _adminRepository.Update(timesheet);
				return RedirectToAction("TimesheetList");
			}
			return View(timesheet);
		}

		// GET: Timesheet/Delete/5
		public async Task<IActionResult> Delete(int id)
		{
			var timesheet = await _employeeRepository.GetTimesheetById(id);
			if (timesheet == null)
			{
				return NotFound();
			}
			return View(timesheet);
		}

		// POST: Timesheet/Delete/5
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> DeleteConfirmed(int id)
		{
			var timesheet = await _employeeRepository.GetTimesheetById(id);
			await _adminRepository.DeleteTimesheet(timesheet);
			return RedirectToAction("TimesheetList");
		}

		public async Task<IActionResult> Permission(int employeeId)
		{
			var employee = await _employeeRepository.GetEmployeeDetails(employeeId);

			if (employee == null)
			{
				return NotFound();
			}

			var pendingTimesheet = employee.Timesheets
				.Where(t => t.Status == "Pending")
				.ToList();

			return View(pendingTimesheet);
		}
		[HttpPost]
		public async Task<IActionResult> ApproveTimesheet(int sheetId)
		{
			var timesheet = await _employeeRepository.GetTimesheetById(sheetId);
			if (timesheet == null)
			{
				return NotFound();
			}

			// Approve the leave and save changes
			timesheet.Status = "Approved";
			await _adminRepository.Update(timesheet);

			return RedirectToAction("Permission", new { employeeId = timesheet.EmployeeId });
		}
		// Action to reject leave
		[HttpPost]
		public async Task<IActionResult> RejectTimesheet(int sheetId)
		{
			var timesheet = await _employeeRepository.GetTimesheetById(sheetId);
			if (timesheet == null)
			{
				return NotFound();
			}

			// Reject the leave and save changes
			timesheet.Status = "Rejected";
			await _adminRepository.Update(timesheet);

			return RedirectToAction("Permission", new { employeeId = timesheet.EmployeeId });
		}
	}
}

Payrollfix_poc/Views/Shared/_AdminHeader.cshtml
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">
    <span class="text-danger">Rithvik Software Solutions</span>
    </a>    
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item">
                <a asp-action="Index" class="nav-link">Dashboard</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Payroll</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Invoice</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Quotation</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <img src=imagepath alt="User Profile" class="rounded-circle" style="width: 35px; height: 35px;">
                </a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
                    <a asp-controller="Admin" asp-action="Dashboard" class="dropdown-item">Profile</a>
                    <a asp-controller="Home" asp-action="EmployeeLogout" class="dropdown-item">Logout</a>
                </div>
            </li>
        </ul>
    </div>
</nav>

Payrollfix_poc/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - PayRollFix</title>
	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
	<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
	<link rel="stylesheet" href="~/PayRollFix.styles.css" asp-append-version="true" />
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
	<link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;600;700&display=swap" rel="stylesheet">
	<link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet" />
	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
	<link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet" />


</head>
<body>
	@await Html.PartialAsync("_AdminHeader")
	<div class="container">
		<main role="main" class="pb-3">
			@RenderBody()
		</main>
	</div>

	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>
	<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.1/umd/popper.min.js"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>


	@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Payrollfix_poc/Views/Shared/_EmployeeHeader.cshtml
@model dynamic
<div class="container-fluid">
	<div class="row">
		<!-- Sidebar Navigation -->
		<div class="col-md-2 d-none d-md-block">
			<!-- Hidden on small screens -->
			@await Html.PartialAsync("_NavbarPartial") <!-- Include your navbar -->
		</div>

		<div class="col-md-10 col-sm-12 px-0">
			<header class="navbar navbar-expand-lg navbar-light bg-white border-bottom">
				<div class="container-fluid">
					<a class="navbar-brand" href="#">
@* 						<img src="@Url.Action("GetImage", "Admin", new { employeeId = Model.EmployeeId })" alt="Company Logo" class="d-inline-block align-top" style="width: 30px; height: 30px;">
 *@						<span class="text-danger">Rithvik Software Solutions</span>
					</a>
					<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
						<span class="navbar-toggler-icon"></span>
					</button>
					<div class="collapse navbar-collapse" id="navbarNav">
						<ul class="navbar-nav ml-auto">
							<li class="nav-item">
								<a class="nav-link" href="#">
									<i class="fas fa-search"></i>
								</a>
							</li>
							<li class="nav-item">
								<a class="nav-link" href="#">
									<i class="fas fa-question-circle"></i> Help
								</a>
							</li>
							<li class="nav-item">
								<a class="nav-link" href="#">
									<i class="fas fa-bell"></i>
								</a>
							</li>
							<li class="nav-item">
								<a asp-action="ResetPassword" class="nav-link">
									<i class="fas fa-cog"></i>
								</a>
							</li>
							<li>
								<button id="theme-toggle">Toggle Theme</button>
							</li>
							<li class="nav-item dropdown">
								<a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
									<img src="@Url.Action("GetHeaderData", "Home")" alt="user profile" class="rounded-circle" style="width: 35px; height: 35px;">
								</a>
								<div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
									<a asp-controller="Employee" asp-action="Dashboard" class="dropdown-item">Profile</a>
									<a asp-controller="Home" asp-action="EmployeeLogout" class="dropdown-item">Logout</a>
								</div>
							</li>
						</ul>
					</div>
				</div>
			</header>
		</div>
	</div>
</div>

<script src="~/js/theme-toggle.js"></script>

Payrollfix_poc/Views/Shared/_EmployeeLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - PayRollFix</title>
	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
	<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
	<link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;600;700&display=swap" rel="stylesheet">
	<link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet" />
	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
	<link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet" />

	@await Html.PartialAsync("_EmployeeHeader", new Payrollfix_poc.Models.Employee())
</head>
<body>
	<div class="container">
		<main role="main" class="pb-3">
			@await Html.PartialAsync("_NavbarPartial");
			@RenderBody();
		</main>

	</div>
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>
	<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.1/umd/popper.min.js"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/microsoft-signalr/5.0.11/signalr.min.js"></script>
	<script>
		const connection = new signalR.HubConnectionBuilder()
			.withUrl("/notificationHub")
			.build();

		connection.start()
			.then(function () {
				console.log("SignalR kdsjfhlsd Connected.");
			})
			.catch(function (err) {
				console.error("Error connecting to SignalR:", err.toString());
			});

		// Listen for leave status updates
		connection.on("ReceiveLeaveStatusUpdate", (leaveId, newStatus) => {
			console.log(`Leave ID: ${leaveId} status updated to: ${newStatus}`);
			// Update the UI based on the new status
			document.querySelector(`#leaveStatus-${leaveId}`).innerText = newStatus;
		});

		// Listen for expense status updates
		connection.on("ReceiveExpenseStatusUpdate", (expenseId, newStatus) => {
			console.log(`Expense ID: ${expenseId} status updated to: ${newStatus}`);
			// Update the UI based on the new status
			document.querySelector(`#expenseStatus-${expenseId}`).innerText = newStatus;
		});

	</script>
	@* @await RenderSectionAsync("Scripts", required: false) *@
</body>
</html>

Payrollfix_poc/Views/Shared/_NavbarPartial.cshtml
<link rel="stylesheet" href="~/css/Navbar.css" />
@{
	string name = ViewBag.PartialView;
}
<div class="col-md-2">
	<div class="sidebar" id="sidebar">
		@* <div class="logo">
		<a href="#">
		<img src="~/images/logo.png" alt="Logo" />
		</a>
		</div> *@
		<div class="list-group">
			<a class="list-group-item list-group-item-action @ViewData["ActiveDashboard"]" asp-controller="Employee" asp-action="Dashboard">
				<i class="fa fa-home"></i> Dashboard
			</a>
			<a class="list-group-item list-group-item-action @ViewData["ActiveLoginDetails"]" asp-controller="Employee" asp-action="LoginDetails">
				<i class="fa fa-user"></i> Login Details
			</a>
			<a class="list-group-item list-group-item-action @ViewData["ActiveAttendance"]" asp-controller="Employee" asp-action="AM">
				<i class="fa fa-calendar"></i> Attendance
			</a>
			@if (name != "Admin")
			{
				<a class="list-group-item list-group-item-action @ViewData["ActiveLeaves"]" asp-controller="Leave" asp-action="LeaveDetails">
					<i class="fa fa-file-alt"></i> Leaves
				</a>
			}
			<a class="list-group-item list-group-item-action @ViewData["ActiveTimesheet"]" asp-controller="Timesheet" asp-action="TimeSheetList">
				<i class="fa fa-clock"></i> Timesheet
			</a>
			<a class="list-group-item list-group-item-action @ViewData["ActiveEmployee"]" asp-controller="Employee" asp-action="Organization">
				<i class="fas fa-globe"></i> Organization
			</a>
			<a class="list-group-item list-group-item-action @ViewData["ActiveMyTeam"]" asp-controller="Employee" asp-action="MyTeam">
				<i class="fa fa-users"></i> My Team
			</a>
			<a class="list-group-item list-group-item-action @ViewData["ActiveExpenses"]" asp-controller="Expense" asp-action="Index">
				<i class="fa fa-wallet"></i> Expenses
			</a>
			@if (name == "Admin")
			{
				<a class="list-group-item list-group-item-action @ViewData["ActiveAdmin"]
						" asp-controller="Admin" asp-action="Index">
					<i class="fas fa-id-card"></i> Admin Settings
				</a>
			}
			<a class="list-group-item list-group-item-action logout @ViewData["ActiveLogout"]" asp-controller="Home" asp-action="EmployeeLogout">
				<i class="fa fa-sign-out-alt"></i> Logout
			</a>
		</div>
	</div>
</div>

<script src="~/js/Navbar.js" asp-append-version="true"></script>